// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: common/v1/security.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthRule describes the trusted caller identity required by an RPC.
// Internal services may obtain that identity from Gateway metadata protected
// by mTLS; this option does not require every service to re-parse external JWTs.
// Methods without this option are protected by default.
type AuthRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public methods do not require an authenticated end-user identity.
	Public bool `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	// 允许访问该方法的角色。
	Roles         []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRule) Reset() {
	*x = AuthRule{}
	mi := &file_common_v1_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRule) ProtoMessage() {}

func (x *AuthRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRule.ProtoReflect.Descriptor instead.
func (*AuthRule) Descriptor() ([]byte, []int) {
	return file_common_v1_security_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRule) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *AuthRule) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var file_common_v1_security_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthRule)(nil),
		Field:         50000,
		Name:          "common.v1.auth",
		Tag:           "bytes,50000,opt,name=auth",
		Filename:      "common/v1/security.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional common.v1.AuthRule auth = 50000;
	E_Auth = &file_common_v1_security_proto_extTypes[0]
)

var File_common_v1_security_proto protoreflect.FileDescriptor

const file_common_v1_security_proto_rawDesc = "" +
	"\n" +
	"\x18common/v1/security.proto\x12\tcommon.v1\x1a google/protobuf/descriptor.proto\"8\n" +
	"\bAuthRule\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles:I\n" +
	"\x04auth\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x13.common.v1.AuthRuleR\x04authB@Z>github.com/Erain-byte/grpc_go_project/proto/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_security_proto_rawDescOnce sync.Once
	file_common_v1_security_proto_rawDescData []byte
)

func file_common_v1_security_proto_rawDescGZIP() []byte {
	file_common_v1_security_proto_rawDescOnce.Do(func() {
		file_common_v1_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_security_proto_rawDesc), len(file_common_v1_security_proto_rawDesc)))
	})
	return file_common_v1_security_proto_rawDescData
}

var file_common_v1_security_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_security_proto_goTypes = []any{
	(*AuthRule)(nil),                   // 0: common.v1.AuthRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_common_v1_security_proto_depIdxs = []int32{
	1, // 0: common.v1.auth:extendee -> google.protobuf.MethodOptions
	0, // 1: common.v1.auth:type_name -> common.v1.AuthRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_security_proto_init() }
func file_common_v1_security_proto_init() {
	if File_common_v1_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_security_proto_rawDesc), len(file_common_v1_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_security_proto_goTypes,
		DependencyIndexes: file_common_v1_security_proto_depIdxs,
		MessageInfos:      file_common_v1_security_proto_msgTypes,
		ExtensionInfos:    file_common_v1_security_proto_extTypes,
	}.Build()
	File_common_v1_security_proto = out.File
	file_common_v1_security_proto_goTypes = nil
	file_common_v1_security_proto_depIdxs = nil
}
