// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: llm/llm.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRole int32

const (
	ChatRole_CHAT_ROLE_UNSPECIFIED ChatRole = 0
	ChatRole_CHAT_ROLE_SYSTEM      ChatRole = 1
	ChatRole_CHAT_ROLE_USER        ChatRole = 2
	ChatRole_CHAT_ROLE_ASSISTANT   ChatRole = 3
	ChatRole_CHAT_ROLE_TOOL        ChatRole = 4
)

// Enum value maps for ChatRole.
var (
	ChatRole_name = map[int32]string{
		0: "CHAT_ROLE_UNSPECIFIED",
		1: "CHAT_ROLE_SYSTEM",
		2: "CHAT_ROLE_USER",
		3: "CHAT_ROLE_ASSISTANT",
		4: "CHAT_ROLE_TOOL",
	}
	ChatRole_value = map[string]int32{
		"CHAT_ROLE_UNSPECIFIED": 0,
		"CHAT_ROLE_SYSTEM":      1,
		"CHAT_ROLE_USER":        2,
		"CHAT_ROLE_ASSISTANT":   3,
		"CHAT_ROLE_TOOL":        4,
	}
)

func (x ChatRole) Enum() *ChatRole {
	p := new(ChatRole)
	*p = x
	return p
}

func (x ChatRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRole) Descriptor() protoreflect.EnumDescriptor {
	return file_llm_llm_proto_enumTypes[0].Descriptor()
}

func (ChatRole) Type() protoreflect.EnumType {
	return &file_llm_llm_proto_enumTypes[0]
}

func (x ChatRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRole.Descriptor instead.
func (ChatRole) EnumDescriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{0}
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_llm_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reply          string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Usage          *TokenUsage            `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_llm_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChatResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type StreamChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamChatRequest) Reset() {
	*x = StreamChatRequest{}
	mi := &file_llm_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatRequest) ProtoMessage() {}

func (x *StreamChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatRequest.ProtoReflect.Descriptor instead.
func (*StreamChatRequest) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{2}
}

func (x *StreamChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StreamChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamChatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Delta          string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Finished       bool                   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	FinishReason   string                 `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Usage          *TokenUsage            `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamChatResponse) Reset() {
	*x = StreamChatResponse{}
	mi := &file_llm_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatResponse) ProtoMessage() {}

func (x *StreamChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatResponse.ProtoReflect.Descriptor instead.
func (*StreamChatResponse) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{3}
}

func (x *StreamChatResponse) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *StreamChatResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StreamChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamChatResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *StreamChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *StreamChatResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_llm_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type GetChatHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_llm_llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatHistoryRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_llm_llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          ChatRole               `protobuf:"varint,2,opt,name=role,proto3,enum=llm.v1.ChatRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRole() ChatRole {
	if x != nil {
		return x.Role
	}
	return ChatRole_CHAT_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetChatListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatListRequest) Reset() {
	*x = GetChatListRequest{}
	mi := &file_llm_llm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatListRequest) ProtoMessage() {}

func (x *GetChatListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatListRequest.ProtoReflect.Descriptor instead.
func (*GetChatListRequest) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChatListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetChatListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatListResponse) Reset() {
	*x = GetChatListResponse{}
	mi := &file_llm_llm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatListResponse) ProtoMessage() {}

func (x *GetChatListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatListResponse.ProtoReflect.Descriptor instead.
func (*GetChatListResponse) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatListResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *GetChatListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Conversation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LastMessageTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_message_time,json=lastMessageTime,proto3" json:"last_message_time,omitempty"`
	MessageCount    int64                  `protobuf:"varint,5,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_llm_llm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{10}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Conversation) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Conversation) GetLastMessageTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageTime
	}
	return nil
}

func (x *Conversation) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type CallModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallModelRequest) Reset() {
	*x = CallModelRequest{}
	mi := &file_llm_llm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallModelRequest) ProtoMessage() {}

func (x *CallModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallModelRequest.ProtoReflect.Descriptor instead.
func (*CallModelRequest) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{11}
}

func (x *CallModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CallModelRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CallModelRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CallModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallModelResponse) Reset() {
	*x = CallModelResponse{}
	mi := &file_llm_llm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallModelResponse) ProtoMessage() {}

func (x *CallModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_llm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallModelResponse.ProtoReflect.Descriptor instead.
func (*CallModelResponse) Descriptor() ([]byte, []int) {
	return file_llm_llm_proto_rawDescGZIP(), []int{12}
}

func (x *CallModelResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CallModelResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_llm_llm_proto protoreflect.FileDescriptor

const file_llm_llm_proto_rawDesc = "" +
	"\n" +
	"\rllm/llm.proto\x12\x06llm.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe0\x01\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x05usage\x18\x06 \x01(\v2\x12.llm.v1.TokenUsageR\x05usage\"\xbf\x01\n" +
	"\x11StreamChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd4\x01\n" +
	"\x12StreamChatResponse\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1a\n" +
	"\bfinished\x18\x04 \x01(\bR\bfinished\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12(\n" +
	"\x05usage\x18\x06 \x01(\v2\x12.llm.v1.TokenUsageR\x05usage\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\x87\x01\n" +
	"\x15GetChatHistoryRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"j\n" +
	"\x16GetChatHistoryResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.llm.v1.ChatMessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x98\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04role\x18\x02 \x01(\x0e2\x10.llm.v1.ChatRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"r\n" +
	"\x12GetChatListRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offsetJ\x04\b\x01\x10\x02R\x0fconversation_id\"r\n" +
	"\x13GetChatListResponse\x12:\n" +
	"\rconversations\x18\x01 \x03(\v2\x14.llm.v1.ConversationR\rconversations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xd3\x01\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12F\n" +
	"\x11last_message_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastMessageTime\x12#\n" +
	"\rmessage_count\x18\x05 \x01(\x03R\fmessageCount\"w\n" +
	"\x10CallModelRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"U\n" +
	"\x11CallModelResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12(\n" +
	"\x05usage\x18\x02 \x01(\v2\x12.llm.v1.TokenUsageR\x05usage*|\n" +
	"\bChatRole\x12\x19\n" +
	"\x15CHAT_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CHAT_ROLE_SYSTEM\x10\x01\x12\x12\n" +
	"\x0eCHAT_ROLE_USER\x10\x02\x12\x17\n" +
	"\x13CHAT_ROLE_ASSISTANT\x10\x03\x12\x12\n" +
	"\x0eCHAT_ROLE_TOOL\x10\x042\xe1\x02\n" +
	"\n" +
	"LlmService\x121\n" +
	"\x04Chat\x12\x13.llm.v1.ChatRequest\x1a\x14.llm.v1.ChatResponse\x12E\n" +
	"\n" +
	"StreamChat\x12\x19.llm.v1.StreamChatRequest\x1a\x1a.llm.v1.StreamChatResponse0\x01\x12O\n" +
	"\x0eGetChatHistory\x12\x1d.llm.v1.GetChatHistoryRequest\x1a\x1e.llm.v1.GetChatHistoryResponse\x12F\n" +
	"\vGetChatList\x12\x1a.llm.v1.GetChatListRequest\x1a\x1b.llm.v1.GetChatListResponse\x12@\n" +
	"\tCallModel\x12\x18.llm.v1.CallModelRequest\x1a\x19.llm.v1.CallModelResponseB5Z3github.com/Erain-byte/grpc_go_project/proto/llm;llmb\x06proto3"

var (
	file_llm_llm_proto_rawDescOnce sync.Once
	file_llm_llm_proto_rawDescData []byte
)

func file_llm_llm_proto_rawDescGZIP() []byte {
	file_llm_llm_proto_rawDescOnce.Do(func() {
		file_llm_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_llm_proto_rawDesc), len(file_llm_llm_proto_rawDesc)))
	})
	return file_llm_llm_proto_rawDescData
}

var file_llm_llm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llm_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_llm_llm_proto_goTypes = []any{
	(ChatRole)(0),                  // 0: llm.v1.ChatRole
	(*ChatRequest)(nil),            // 1: llm.v1.ChatRequest
	(*ChatResponse)(nil),           // 2: llm.v1.ChatResponse
	(*StreamChatRequest)(nil),      // 3: llm.v1.StreamChatRequest
	(*StreamChatResponse)(nil),     // 4: llm.v1.StreamChatResponse
	(*TokenUsage)(nil),             // 5: llm.v1.TokenUsage
	(*GetChatHistoryRequest)(nil),  // 6: llm.v1.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil), // 7: llm.v1.GetChatHistoryResponse
	(*ChatMessage)(nil),            // 8: llm.v1.ChatMessage
	(*GetChatListRequest)(nil),     // 9: llm.v1.GetChatListRequest
	(*GetChatListResponse)(nil),    // 10: llm.v1.GetChatListResponse
	(*Conversation)(nil),           // 11: llm.v1.Conversation
	(*CallModelRequest)(nil),       // 12: llm.v1.CallModelRequest
	(*CallModelResponse)(nil),      // 13: llm.v1.CallModelResponse
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 15: google.protobuf.Struct
}
var file_llm_llm_proto_depIdxs = []int32{
	14, // 0: llm.v1.ChatRequest.timestamp:type_name -> google.protobuf.Timestamp
	14, // 1: llm.v1.ChatResponse.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: llm.v1.ChatResponse.usage:type_name -> llm.v1.TokenUsage
	14, // 3: llm.v1.StreamChatRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 4: llm.v1.StreamChatResponse.usage:type_name -> llm.v1.TokenUsage
	8,  // 5: llm.v1.GetChatHistoryResponse.messages:type_name -> llm.v1.ChatMessage
	0,  // 6: llm.v1.ChatMessage.role:type_name -> llm.v1.ChatRole
	14, // 7: llm.v1.ChatMessage.created_at:type_name -> google.protobuf.Timestamp
	11, // 8: llm.v1.GetChatListResponse.conversations:type_name -> llm.v1.Conversation
	14, // 9: llm.v1.Conversation.last_message_time:type_name -> google.protobuf.Timestamp
	15, // 10: llm.v1.CallModelRequest.parameters:type_name -> google.protobuf.Struct
	5,  // 11: llm.v1.CallModelResponse.usage:type_name -> llm.v1.TokenUsage
	1,  // 12: llm.v1.LlmService.Chat:input_type -> llm.v1.ChatRequest
	3,  // 13: llm.v1.LlmService.StreamChat:input_type -> llm.v1.StreamChatRequest
	6,  // 14: llm.v1.LlmService.GetChatHistory:input_type -> llm.v1.GetChatHistoryRequest
	9,  // 15: llm.v1.LlmService.GetChatList:input_type -> llm.v1.GetChatListRequest
	12, // 16: llm.v1.LlmService.CallModel:input_type -> llm.v1.CallModelRequest
	2,  // 17: llm.v1.LlmService.Chat:output_type -> llm.v1.ChatResponse
	4,  // 18: llm.v1.LlmService.StreamChat:output_type -> llm.v1.StreamChatResponse
	7,  // 19: llm.v1.LlmService.GetChatHistory:output_type -> llm.v1.GetChatHistoryResponse
	10, // 20: llm.v1.LlmService.GetChatList:output_type -> llm.v1.GetChatListResponse
	13, // 21: llm.v1.LlmService.CallModel:output_type -> llm.v1.CallModelResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_llm_llm_proto_init() }
func file_llm_llm_proto_init() {
	if File_llm_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_llm_proto_rawDesc), len(file_llm_llm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_llm_proto_goTypes,
		DependencyIndexes: file_llm_llm_proto_depIdxs,
		EnumInfos:         file_llm_llm_proto_enumTypes,
		MessageInfos:      file_llm_llm_proto_msgTypes,
	}.Build()
	File_llm_llm_proto = out.File
	file_llm_llm_proto_goTypes = nil
	file_llm_llm_proto_depIdxs = nil
}
