// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: llm/llm.proto

package llm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LlmService_Chat_FullMethodName           = "/llm.v1.LlmService/Chat"
	LlmService_StreamChat_FullMethodName     = "/llm.v1.LlmService/StreamChat"
	LlmService_GetChatHistory_FullMethodName = "/llm.v1.LlmService/GetChatHistory"
	LlmService_GetChatList_FullMethodName    = "/llm.v1.LlmService/GetChatList"
	LlmService_CallModel_FullMethodName      = "/llm.v1.LlmService/CallModel"
)

// LlmServiceClient is the client API for LlmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	StreamChat(ctx context.Context, in *StreamChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatResponse], error)
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error)
	GetChatList(ctx context.Context, in *GetChatListRequest, opts ...grpc.CallOption) (*GetChatListResponse, error)
	CallModel(ctx context.Context, in *CallModelRequest, opts ...grpc.CallOption) (*CallModelResponse, error)
}

type llmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmServiceClient(cc grpc.ClientConnInterface) LlmServiceClient {
	return &llmServiceClient{cc}
}

func (c *llmServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, LlmService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmServiceClient) StreamChat(ctx context.Context, in *StreamChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LlmService_ServiceDesc.Streams[0], LlmService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChatRequest, StreamChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LlmService_StreamChatClient = grpc.ServerStreamingClient[StreamChatResponse]

func (c *llmServiceClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatHistoryResponse)
	err := c.cc.Invoke(ctx, LlmService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmServiceClient) GetChatList(ctx context.Context, in *GetChatListRequest, opts ...grpc.CallOption) (*GetChatListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatListResponse)
	err := c.cc.Invoke(ctx, LlmService_GetChatList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmServiceClient) CallModel(ctx context.Context, in *CallModelRequest, opts ...grpc.CallOption) (*CallModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallModelResponse)
	err := c.cc.Invoke(ctx, LlmService_CallModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmServiceServer is the server API for LlmService service.
// All implementations must embed UnimplementedLlmServiceServer
// for forward compatibility.
type LlmServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	StreamChat(*StreamChatRequest, grpc.ServerStreamingServer[StreamChatResponse]) error
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error)
	GetChatList(context.Context, *GetChatListRequest) (*GetChatListResponse, error)
	CallModel(context.Context, *CallModelRequest) (*CallModelResponse, error)
	mustEmbedUnimplementedLlmServiceServer()
}

// UnimplementedLlmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmServiceServer struct{}

func (UnimplementedLlmServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLlmServiceServer) StreamChat(*StreamChatRequest, grpc.ServerStreamingServer[StreamChatResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedLlmServiceServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedLlmServiceServer) GetChatList(context.Context, *GetChatListRequest) (*GetChatListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatList not implemented")
}
func (UnimplementedLlmServiceServer) CallModel(context.Context, *CallModelRequest) (*CallModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallModel not implemented")
}
func (UnimplementedLlmServiceServer) mustEmbedUnimplementedLlmServiceServer() {}
func (UnimplementedLlmServiceServer) testEmbeddedByValue()                    {}

// UnsafeLlmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmServiceServer will
// result in compilation errors.
type UnsafeLlmServiceServer interface {
	mustEmbedUnimplementedLlmServiceServer()
}

func RegisterLlmServiceServer(s grpc.ServiceRegistrar, srv LlmServiceServer) {
	// If the following call panics, it indicates UnimplementedLlmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmService_ServiceDesc, srv)
}

func _LlmService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LlmServiceServer).StreamChat(m, &grpc.GenericServerStream[StreamChatRequest, StreamChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LlmService_StreamChatServer = grpc.ServerStreamingServer[StreamChatResponse]

func _LlmService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmService_GetChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).GetChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_GetChatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).GetChatList(ctx, req.(*GetChatListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmService_CallModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).CallModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_CallModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).CallModel(ctx, req.(*CallModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LlmService_ServiceDesc is the grpc.ServiceDesc for LlmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.v1.LlmService",
	HandlerType: (*LlmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _LlmService_Chat_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _LlmService_GetChatHistory_Handler,
		},
		{
			MethodName: "GetChatList",
			Handler:    _LlmService_GetChatList_Handler,
		},
		{
			MethodName: "CallModel",
			Handler:    _LlmService_CallModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _LlmService_StreamChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm/llm.proto",
}
