# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llm.v1 import llm_pb2 as llm_dot_v1_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm/v1/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/llm.v1.LlmService/Chat',
                request_serializer=llm_dot_v1_dot_llm__pb2.ChatRequest.SerializeToString,
                response_deserializer=llm_dot_v1_dot_llm__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/llm.v1.LlmService/StreamChat',
                request_serializer=llm_dot_v1_dot_llm__pb2.StreamChatRequest.SerializeToString,
                response_deserializer=llm_dot_v1_dot_llm__pb2.StreamChatResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/llm.v1.LlmService/GetChatHistory',
                request_serializer=llm_dot_v1_dot_llm__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=llm_dot_v1_dot_llm__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)
        self.GetChatList = channel.unary_unary(
                '/llm.v1.LlmService/GetChatList',
                request_serializer=llm_dot_v1_dot_llm__pb2.GetChatListRequest.SerializeToString,
                response_deserializer=llm_dot_v1_dot_llm__pb2.GetChatListResponse.FromString,
                _registered_method=True)
        self.CallModel = channel.unary_unary(
                '/llm.v1.LlmService/CallModel',
                request_serializer=llm_dot_v1_dot_llm__pb2.CallModelRequest.SerializeToString,
                response_deserializer=llm_dot_v1_dot_llm__pb2.CallModelResponse.FromString,
                _registered_method=True)


class LlmServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=llm_dot_v1_dot_llm__pb2.ChatRequest.FromString,
                    response_serializer=llm_dot_v1_dot_llm__pb2.ChatResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=llm_dot_v1_dot_llm__pb2.StreamChatRequest.FromString,
                    response_serializer=llm_dot_v1_dot_llm__pb2.StreamChatResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=llm_dot_v1_dot_llm__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=llm_dot_v1_dot_llm__pb2.GetChatHistoryResponse.SerializeToString,
            ),
            'GetChatList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatList,
                    request_deserializer=llm_dot_v1_dot_llm__pb2.GetChatListRequest.FromString,
                    response_serializer=llm_dot_v1_dot_llm__pb2.GetChatListResponse.SerializeToString,
            ),
            'CallModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CallModel,
                    request_deserializer=llm_dot_v1_dot_llm__pb2.CallModelRequest.FromString,
                    response_serializer=llm_dot_v1_dot_llm__pb2.CallModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.v1.LlmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.v1.LlmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LlmService/Chat',
            llm_dot_v1_dot_llm__pb2.ChatRequest.SerializeToString,
            llm_dot_v1_dot_llm__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.v1.LlmService/StreamChat',
            llm_dot_v1_dot_llm__pb2.StreamChatRequest.SerializeToString,
            llm_dot_v1_dot_llm__pb2.StreamChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LlmService/GetChatHistory',
            llm_dot_v1_dot_llm__pb2.GetChatHistoryRequest.SerializeToString,
            llm_dot_v1_dot_llm__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LlmService/GetChatList',
            llm_dot_v1_dot_llm__pb2.GetChatListRequest.SerializeToString,
            llm_dot_v1_dot_llm__pb2.GetChatListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LlmService/CallModel',
            llm_dot_v1_dot_llm__pb2.CallModelRequest.SerializeToString,
            llm_dot_v1_dot_llm__pb2.CallModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
